name: OnTime
version: "0.1.0"
main: org.anvilpowered.ontime.spigot.plugin.OnTimeSpigot
api-version: 1.15
authors: [Cableguy20, STG_Allen]
description: Playtime tracker
depend: [Anvil, LuckPerms]
commands:
  ontime:
    description: OnTime root command
