# This is not intended to be a production-ready deployment; It is only intended to demonstrate
# how OnTime may be deployed in a container environment.
# Carefully read and understand the entire configuration before using any part of it.
# By using this file, you are indicating your acceptance of the Minecraft EULA (https://www.minecraft.net/en-us/eula).
name: ontime-paper

services:
  db:
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ontime_docker_compose
      POSTGRES_USER: ontime_docker_compose
      POSTGRES_PASSWORD: ontime_docker_compose
    volumes:
      - ./db:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:8.3
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ontime@example.com
      PGADMIN_DEFAULT_PASSWORD: ontime

  lp:
    image: ghcr.io/luckperms/luckperms:v5.4.144
    environment:
      LUCKPERMS_STORAGE_METHOD: postgresql
      LUCKPERMS_DATA_ADDRESS: db
      # Use a different database and credentials in production
      LUCKPERMS_DATA_DATABASE: ontime_docker_compose
      LUCKPERMS_DATA_USERNAME: ontime_docker_compose
      LUCKPERMS_DATA_PASSWORD: ontime_docker_compose

  paper:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    environment:
      TYPE: PAPER
      VERSION: "1.20.6"
      EULA: true # By using this environment variable, you are indicating your acceptance of the Minecraft EULA
      ONLINE_MODE: true
      PLUGINS: |
        https://download.luckperms.net/1549/bukkit/loader/LuckPerms-Bukkit-5.4.134.jar
      ONTIME_DB_URL: jdbc:postgresql://db/ontime_docker_compose
      ONTIME_DB_USER: ontime_docker_compose
      ONTIME_DB_PASSWORD: ontime_docker_compose
      ONTIME_RANK_TIMES: |
        {
          "noob": 0,
          "player": 600,
          "trusted": 1800
        }
      ONTIME_RANK_COMMANDS: |
        {
          ".*": [
            "broadcast %username% has advanced to %rank% after playing for %time%",
            "give %username% iron_ingot 1"
          ],
          "trusted": [
            "broadcast %username% is the best"
          ]
        }
    volumes:
      - ../../../build/libs:/plugins
      - ./paper:/data
